
[Network]
  Address = ":19132"

[Players]
  Folder = "players"
  MaxCount = 20
  MaximumChunkRadius = 32
  SaveData = true

[Resources]
  AutoBuildPack = true
  Folder = "resources"
  Required = true

[Server]
  AuthEnabled = true
  JoinMessage = "그의 이름은 바로... %v"
  Name = "Dragonfly Server"
  QuitMessage = "안녕 너를 기억할게. %v"
  ShutdownMessage = "Server closed."

[World]
  Folder = "worlds/play"
  SaveData = true
